[build]
  base = "/opt/build/repo/myPortfolioSite/my-portfolio"
  publish = "/opt/build/repo/myPortfolioSite/my-portfolio/build"
  command = "npm install && npm run build"

[context.production.environment]
  NODE_VERSION = "14"